### ISSUE TITLE
Support for ZUGPFeRD version 2

### ISSUE THREAD

**Issue by pya** [pretix/python-drafthorse#2]
Are there any plans to support ZUGFeRD 2.0?

**Comment by raphaelm** [comment]
We do not have plans since this module sees low usage and version 1 is still pretty supported in the wild, but we're happy to accept any contributions!

**Comment by pya** [comment]
Good to know that version 1 is still widely supported. I am not sure if we actually we will use this module. If so, I might send a PR.
