### ISSUE TITLE
Date of Delivery

### ISSUE THREAD

**Issue by ivegotaquestion** [pretix/python-drafthorse#34]
Hello, 

I want to set the date of delivery. 

I wrote the following example code: 

`delivery = SupplyChainEvent()
delivery.occurrence = date(2000,1,1)`

There is no error but the xml file got no information of "OccurenceDateTime"

**Comment by bwurst** [comment]
Try like this:
doc = Document()
...
doc.trade.delivery.event.occurrence = date( ... )

You don't have to manually initialize the object hierarchy, the fields are just there. 
In your code, you loose the connection in the element tree but have an additional SupplyChainEvent object that does not belong to the document.
