### ISSUE TITLE
payment terms

### ISSUE THREAD

**Issue by ivegotaquestion** [pretix/python-drafthorse#35]
I tried to add payment terms:

`doc = Document()`
`doc.trade.settlement.terms.due = date(2000,1,15)`
`doc.trade.settlement.terms.description = "3% discount until 14.01.2000"`
`doc.trade.settlement.terms.discount_terms.basis_date_time = date(2000,1,14)`
`doc.trade.settlement.terms.discount_terms.basis_amount = Decimal("999.00")`
`doc.trade.settlement.terms.discount_terms.calculation_percent = Decimal("0.10")`

(1) There is an error message for "discount_terms" lines:
 `AttributeError: 'Container' object has no attribute 'discount_terms'`

(2) The due date and description are not listed in the xml file.

**Comment by holvi-epurontaus** [comment]
Try this way:

```python
        payment_terms = PaymentTerms(
            due=my_due_date,
            description="My description",
        )
        payment_terms.discount_terms.basis_date_time=date(2000, 1, 14)
        payment_terms.discount_terms.basis_amount = Decimal("999.00")
        payment_terms.discount_terms.calculation_percent = Decimal("0.10")

        doc.trade.settlement.terms.add(payment_terms)
```

**Comment by epuronta** [comment]
Try this way:

```python
        payment_terms = PaymentTerms(
            due=my_due_date,
            description="My description",
        )
        payment_terms.discount_terms.basis_date_time=date(2000, 1, 14)
        payment_terms.discount_terms.basis_amount = Decimal("999.00")
        payment_terms.discount_terms.calculation_percent = Decimal("0.10")

        doc.trade.settlement.terms.add(payment_terms)
```
