### ISSUE TITLE
Question about the profile level

### ISSUE THREAD

**Issue by RitchiS99** [pretix/python-drafthorse#43]
The Readme says "The profile level is detected automatically based on the XML data and added to the PDF metadata.". Does this mean, that if all fields that are needed for a "x-invoice" this profile is automatically selected? In Germany there is the need of "ZUGFeRD" or "XRechnung" but public clients seems to always need a "ZUGFeRD" invoice with the "XRechnung"-Profile.

**Comment by raphaelm** [comment]
No, you need to set doc.context.guideline_parameter.id manually, the documentation you quoted only means you don't need to pass it to the xml attachment step. *again*

**Comment by RitchiS99** [comment]
Okay, thank you for the quick reply.
