### ISSUE TITLE
Discount and default interest (BT-20)

### ISSUE THREAD

**Issue by JimlyTheReal** [pretix/python-drafthorse#45]
Hello, 

I'm looking for the possibility to transmit discount (SKONTO). According to the definition, this currently has to be done in BT-20 as a string.
[https://www.zugferdpro.com/skonto-und-verzugszinsen-bt-20/]

I'm currently missing the BT-20 area, is there anything else coming?
PaymentTermsDescription

**Comment by raphaelm** [comment]
BT-20 is:

        pt = PaymentTerms()
        pt.description = "Text for BT-20"
        doc.trade.settlement.terms.add(pt)
