### ISSUE TITLE
Wrong subtype for embedded attachment

### ISSUE THREAD

**Issue by umoos** [pretix/python-drafthorse#9]
The method attach_xml() and the subsequent call to _facturx_update_metadata_add_attachment() sets in the file_entry for the key "/Subtype" the value "/text#2fxml", explaining that this represents '/' in hexadecimal. Recent updates (since 11/2022 I think...) of pypdf replaces '/' (see  pypdf/generic/_base: class NameObject) that character automatically. Moreover, it also replaces '#' by b'23' which results eventually in "/text#2fxml" -> "/text#232xml".
This makes compliance validations (e.g. https://www.zugferd-community.net/de/dashboard/validation) fail for the PDF/A part. 
Could be easily solved by replacing "/text#2fxml" by "/text/xml" ?

**Comment by wiffbi** [comment]
Looks like https://github.com/py-pdf/pypdf/commit/fb8be4065bfb26ec3bec71d8c6d65b3be3a2034f introduced the change. Your suggestion looks good, we will look into this.
